# Generated by Django 5.0.7 on 2024-07-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avltests',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
