# Generated by Django 5.0.7 on 2024-07-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_avltests_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvlTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AvlTests',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='patient.avltest'),
        ),
        migrations.AddField(
            model_name='avltest',
            name='city',
            field=models.ManyToManyField(related_name='item', to='patient.city'),
        ),
    ]
