# Generated by Django 5.0.7 on 2024-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_avltest_city_delete_avltests_alter_ordermodel_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avltest',
            name='city',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
